import React from "react";
import AccountPageFrame from "@/components/AccountPageFrame";
import { useTheme, type Palette } from "@/contexts/ThemeContext";
import { ArrowUpRight, Check, Contrast, Moon, Monitor, Palette as PaletteIcon, Sun } from "lucide-react";
import { Link } from "wouter";

type ThemeOption = { id: Palette; lightName: string; darkName: string; lightCombination: string; darkCombination: string; lightBackground: string; lightText: string; lightAccent: string; darkBackground: string; darkSurface: string; darkText: string; darkAccent: string; description: string };

const themes: ThemeOption[] = [
  { id: "obsidian", lightName: "PAPER / INK", darkName: "OBSIDIAN / INK", lightCombination: "Warm White · Black · Burgundy", darkCombination: "True Black · Charcoal · Soft Gray", lightBackground: "#FFFDF8", lightText: "#111111", lightAccent: "#7F1D1D", darkBackground: "#09090B", darkSurface: "#27272A", darkText: "#FAFAFA", darkAccent: "#A1A1AA", description: "High-contrast editorial foundation for focused work." },
  { id: "lavender", lightName: "IVORY / COBALT", darkName: "MIDNIGHT / COBALT", lightCombination: "Ivory · Navy · Cobalt Blue", darkCombination: "Deep Navy · Navy · Cobalt Blue", lightBackground: "#FFFFF5", lightText: "#172554", lightAccent: "#2563EB", darkBackground: "#0B1228", darkSurface: "#172554", darkText: "#FFFFFF", darkAccent: "#60A5FA", description: "A precise blue signal with a polished technical base." },
  { id: "electric", lightName: "CLOUD / INDIGO", darkName: "VOID / VIOLET", lightCombination: "Cool White · Charcoal · Indigo", darkCombination: "Near Black · Deep Purple · Violet", lightBackground: "#F8FAFC", lightText: "#27272A", lightAccent: "#4F46E5", darkBackground: "#0B0714", darkSurface: "#2E1065", darkText: "#EDE9FE", darkAccent: "#8B5CF6", description: "High-energy interface with a charged indigo signal." },
  { id: "midnight", lightName: "PEARL / LAVENDER", darkName: "CARBON / CYAN", lightCombination: "Pearl White · Deep Purple · Lavender", darkCombination: "Carbon Black · Dark Gray · Cyan", lightBackground: "#FFFEFF", lightText: "#3B0764", lightAccent: "#8B5CF6", darkBackground: "#111111", darkSurface: "#27272A", darkText: "#FFFFFF", darkAccent: "#22D3EE", description: "Soft light or cool carbon, tuned for long sessions." },
  { id: "terminal", lightName: "ICE / CYAN", darkName: "TERMINAL / GREEN", lightCombination: "Ice White · Navy · Cyan", darkCombination: "Black · Deep Green · Mint", lightBackground: "#F3FBFF", lightText: "#172554", lightAccent: "#0891B2", darkBackground: "#050505", darkSurface: "#052E16", darkText: "#D1FAE5", darkAccent: "#10B981", description: "A diagnostic-console aesthetic with crisp signal edges." },
  { id: "volt", lightName: "MINT / FOREST", darkName: "VOLT / AMBER", lightCombination: "Soft Mint · Dark Green · Emerald", darkCombination: "Black · Dark Brown · Amber", lightBackground: "#F0FDF4", lightText: "#14532D", lightAccent: "#059669", darkBackground: "#09090B", darkSurface: "#422006", darkText: "#FFFBEB", darkAccent: "#F59E0B", description: "Natural green precision or a high-voltage amber bench." },
  { id: "cyber", lightName: "SAND / AMBER", darkName: "CRIMSON / BLACK", lightCombination: "Warm Sand · Dark Brown · Amber", darkCombination: "Near Black · Dark Burgundy · Red", lightBackground: "#FFFBEB", lightText: "#451A03", lightAccent: "#D97706", darkBackground: "#110507", darkSurface: "#450A0A", darkText: "#FFF1F2", darkAccent: "#EF4444", description: "Warm diagnostic emphasis for warnings and action states." },
  { id: "plasma", lightName: "ROSE / WINE", darkName: "GRAPHITE / LIME", lightCombination: "Soft Rose · Dark Charcoal · Wine", darkCombination: "Graphite · Dark Gray · Lime", lightBackground: "#FFF1F2", lightText: "#3F0A18", lightAccent: "#9F1239", darkBackground: "#27272A", darkSurface: "#3F3F46", darkText: "#FFFFFF", darkAccent: "#A3E635", description: "A distinctive modern signal with strong contrast." },
  { id: "ocean", lightName: "SKY / BLUE", darkName: "DEEP OCEAN", lightCombination: "Pale Blue · Navy · Electric Blue", darkCombination: "Deep Blue · Dark Teal · Aqua", lightBackground: "#EFF6FF", lightText: "#172554", lightAccent: "#2563EB", darkBackground: "#082F49", darkSurface: "#134E4A", darkText: "#ECFEFF", darkAccent: "#22D3EE", description: "Calm, cool instrumentation for an engineering workspace." },
  { id: "circuit", lightName: "LEMON / GRAPHITE", darkName: "PLASMA", lightCombination: "Soft Cream · Graphite · Yellow", darkCombination: "Black · Dark Purple · Magenta", lightBackground: "#FEFCE8", lightText: "#27272A", lightAccent: "#CA8A04", darkBackground: "#09090B", darkSurface: "#3B0764", darkText: "#FAE8FF", darkAccent: "#D946EF", description: "A PCB-inspired split between bright logic and plasma signal." },
  { id: "signal", lightName: "PEACH / ORANGE", darkName: "FOREST / MINT", lightCombination: "Soft Peach · Dark Brown · Orange", darkCombination: "Very Dark Green · Forest · Emerald", lightBackground: "#FFF7ED", lightText: "#431407", lightAccent: "#EA580C", darkBackground: "#052E16", darkSurface: "#14532D", darkText: "#ECFDF5", darkAccent: "#34D399", description: "Warm diagnostic signal in light, calm green focus in dark." },
  { id: "graphite", lightName: "SAGE / OLIVE", darkName: "SLATE / ORANGE", lightCombination: "Soft Sage · Dark Olive · Olive", darkCombination: "Slate · Dark Gray · Orange", lightBackground: "#F7FEE7", lightText: "#365314", lightAccent: "#65A30D", darkBackground: "#1E293B", darkSurface: "#334155", darkText: "#FFFFFF", darkAccent: "#FB923C", description: "Grounded, softer contrast without losing technical clarity." },
  { id: "ice", lightName: "LILAC / VIOLET", darkName: "STEEL / BLUE", lightCombination: "Very Light Lilac · Deep Violet · Violet", darkCombination: "Blue-Gray · Steel · Electric Blue", lightBackground: "#FAF5FF", lightText: "#4C1D95", lightAccent: "#7C3AED", darkBackground: "#1E293B", darkSurface: "#334155", darkText: "#F8FAFC", darkAccent: "#3B82F6", description: "A clean, bright or steel-blue engineering workspace." },
  { id: "sunset", lightName: "AQUA / TEAL", darkName: "ROSE / NIGHT", lightCombination: "Pale Aqua · Dark Teal · Teal", darkCombination: "Near Black · Dark Plum · Rose", lightBackground: "#F0FDFA", lightText: "#134E4A", lightAccent: "#0F766E", darkBackground: "#110A13", darkSurface: "#4A044E", darkText: "#FFF1F2", darkAccent: "#FB7185", description: "A cool aqua signal by day with a vivid night accent." },
  { id: "rose", lightName: "CONCRETE / RED", darkName: "ARCTIC / CYAN", lightCombination: "Light Gray · Charcoal · Signal Red", darkCombination: "Deep Blue-Black · Dark Navy · Cyan", lightBackground: "#F4F4F5", lightText: "#27272A", lightAccent: "#DC2626", darkBackground: "#071522", darkSurface: "#172554", darkText: "#E0F2FE", darkAccent: "#06B6D4", description: "Strong warning red or arctic cyan for decisive feedback." },
  { id: "mono", lightName: "MONO / BLACK", darkName: "MONO / WHITE", lightCombination: "White · Black · Black", darkCombination: "Black · Dark Gray · White", lightBackground: "#FFFFFF", lightText: "#09090B", lightAccent: "#09090B", darkBackground: "#000000", darkSurface: "#27272A", darkText: "#FFFFFF", darkAccent: "#FFFFFF", description: "Minimal monochrome workspace with no visual noise." },
];

export default function VisualSignal() {
  const { theme, preference, setPreference, palette, setPalette, highContrast, toggleHighContrast } = useTheme();
  return <AccountPageFrame kicker="IDK / VISUAL SIGNAL" title={<>VISUAL<br /><em>SIGNAL.</em></>} description="Choose the visual language of your IDK workspace.">
    <Link className="visual-signal-back text-link" href="/settings">← BACK TO SETTINGS</Link>
    <div className="visual-signal-layout">
      <section className="visual-signal-card visual-signal-mode"><div className="visual-signal-heading"><Monitor size={20} /><span className="mono">01 / MODE</span></div><h2>LIGHT, DARK, OR SYSTEM.</h2><p>Choose the surface mode independently from the paired color signal. Current mode: <strong>{preference.toUpperCase()}</strong> / rendered <strong>{theme.toUpperCase()}</strong>.</p><div className="visual-signal-mode-grid"><button type="button" aria-pressed={preference === "light"} onClick={() => setPreference("light")}><Sun size={16} /> LIGHT {preference === "light" && <Check size={14} />}</button><button type="button" aria-pressed={preference === "dark"} onClick={() => setPreference("dark")}><Moon size={16} /> DARK {preference === "dark" && <Check size={14} />}</button><button type="button" aria-pressed={preference === "system"} onClick={() => setPreference("system")}><Monitor size={16} /> SYSTEM {preference === "system" && <Check size={14} />}</button></div></section>
      <section className="visual-signal-card visual-signal-wide"><div className="visual-signal-heading"><PaletteIcon size={20} /><span className="mono">02 / COLOR SIGNAL</span></div><h2>CHOOSE YOUR SIGNAL.</h2><p>Select a paired light/dark color language for your IDK workspace. The active mode determines which half of the theme pair is rendered.</p><div className="palette-grid">{themes.map((item, index) => <button type="button" key={item.id} className={`palette-choice palette-choice-${item.id}`} aria-pressed={palette === item.id} aria-label={`Select ${item.lightName} in light mode or ${item.darkName} in dark mode`} onClick={() => setPalette(item.id)}><span className="palette-preview palette-preview-paired" style={{ "--preview-primary": theme === "light" ? item.lightBackground : item.darkBackground, "--preview-secondary": theme === "light" ? item.lightAccent : item.darkAccent, "--preview-text": theme === "light" ? item.lightText : item.darkText } as React.CSSProperties}><i /><i /><b>LIGHT / DARK</b></span><span className="palette-choice-copy"><strong>{String(index + 1).padStart(2, "0")} — {theme === "light" ? item.lightName : item.darkName}</strong><small>{theme === "light" ? item.lightCombination : item.darkCombination}</small><em>{item.description}</em></span><span className="palette-choice-state">{palette === item.id ? <><Check size={14} /> ACTIVE</> : "SELECT"}</span></button>)}</div></section>
      <section className="visual-signal-card visual-signal-wide"><div className="visual-signal-heading"><Contrast size={20} /><span className="mono">03 / READABILITY</span></div><h2>HIGH CONTRAST IS A SIGNAL, TOO.</h2><p>Increase border, focus, and text separation when you need a stronger read. This preference remains available from this page and the Home appearance menu.</p><button className="button button-outline" type="button" aria-pressed={highContrast} onClick={toggleHighContrast}>{highContrast ? "DISABLE HIGH CONTRAST" : "ENABLE HIGH CONTRAST"} <ArrowUpRight size={15} /></button></section>
      <div className="visual-signal-footer"><Link className="text-link" href="/settings">← BACK TO SETTINGS <ArrowUpRight size={15} /></Link><Link className="text-link" href="/personalization">TUNE KERNEL BEHAVIOUR <ArrowUpRight size={15} /></Link></div>
    </div>
  </AccountPageFrame>;
}
